version: '3'

services:
  rails:
    build: .
    command: ruby bin/rails_docker
    volumes:
      - .:/app
    links:
      - postgres
    ports:
      - "3000:3000"
    expose:
      - "3000"

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .:/app
    ports:
      - "5432:5432"
    expose:
      - "5432"

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - "6379"

  sidekiq:
    build: .
    command: ruby bin/sidekiq_docker
    links:
      - redis
      - rails
      - postgres
    volumes:
      - .:/app
